self-hosted-runner:
  # Labels of self-hosted or not-yet-known-upstream runner in array of strings.
  labels: []
# Configuration variables in array of strings defined in your repository or
# organization. `null` means disabling configuration variables check.
# Empty array means no configuration variable is allowed.
config-variables:
  - BREW_COMMIT_APP_ID
