# frozen_string_literal: true

source "https://rubygems.org"

ruby file: ".ruby-version"

gem "github-pages", group: :jekyll_plugins

gem "csv"
gem "faraday-retry"
gem "logger"
gem "redcarpet"
gem "yard"
gem "yard-sorbet"

group :test do
  gem "html-proofer"
  gem "mdl"
  gem "rake"
  gem "webrick"
end
